name: CI
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependências
        run: npm install
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - run: npm install --frozen-lockfile
      - run: npm run lint
      - run: npm run test
